name = "NICAMIO"
uuid = "aefe623e-8955-41c1-958e-feea0b274d8e"
authors = ["Chihiro Kodama"]
version = "0.1.0"

[deps]
FortranFiles = "c58ffaec-ab22-586d-bfc5-781a99fd0b10"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"

[compat]
julia = "0.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
